using ROROROblox.Core;

namespace ROROROblox.Tests;

/// <summary>
/// Item 3 (v1.3.x) — verifies the <see cref="RenameTarget"/> DTO compiles and the
/// value-record equality contract behaves as expected for each <see cref="RenameTargetKind"/>.
/// Equality is auto-generated by C#'s positional record syntax, so these tests are
/// guarding the contract more than the language — if a future change converts the
/// record to a class or strips a property, equality semantics drop and these fail.
/// </summary>
public class RenameTargetTests
{
    [Fact]
    public void GameTarget_StructuralEquality_HoldsAcrossSeparateConstructions()
    {
        var a = new RenameTarget(RenameTargetKind.Game, 1L, "Adopt Me", null);
        var b = new RenameTarget(RenameTargetKind.Game, 1L, "Adopt Me", null);

        Assert.Equal(a, b);
        Assert.Equal(a.GetHashCode(), b.GetHashCode());
    }

    [Fact]
    public void DifferentKind_BreaksEquality()
    {
        var id = Guid.NewGuid();
        var asPrivateServer = new RenameTarget(RenameTargetKind.PrivateServer, id, "Squad VIP", "My Squad");
        var asAccount = new RenameTarget(RenameTargetKind.Account, id, "Squad VIP", "My Squad");

        Assert.NotEqual(asPrivateServer, asAccount);
    }

    [Fact]
    public void DifferentCurrentLocalName_BreaksEquality()
    {
        var id = Guid.NewGuid();
        var withOverride = new RenameTarget(RenameTargetKind.Account, id, "TestUser", "Mr. Solo Dolo");
        var withoutOverride = new RenameTarget(RenameTargetKind.Account, id, "TestUser", null);

        Assert.NotEqual(withOverride, withoutOverride);
    }
}
