#!/usr/bin/env python3
"""Generate the public strongly-typed accessor for Strings.resx.

WPF x:Static needs a PUBLIC static member per resx key, and Visual Studio's
PublicResXFileCodeGenerator (the usual source of that class) never runs under
`dotnet build` / CI. So we own the accessor: this script reads the neutral
Strings.resx and emits Properties/Strings.cs with one public static property per
key, each reading through a ResourceManager (so the running thread's
CurrentUICulture resolves to a satellite catalog, neutral fallback).

Re-run after every extraction; ResxAccessorParityFenceTests proves the .cs and
the .resx never drift.

    python scripts/gen-strings-accessor.py
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESX = ROOT / "src" / "ROROROblox.App" / "Properties" / "Strings.resx"
OUT = ROOT / "src" / "ROROROblox.App" / "Properties" / "Strings.cs"

KEY_RE = re.compile(r'<data\s+name="([^"]+)"', re.IGNORECASE)
IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def main() -> None:
    if not RESX.exists():
        raise SystemExit(f"no resx at {RESX}")
    seen: set[str] = set()
    ordered: list[str] = []
    for k in KEY_RE.findall(RESX.read_text(encoding="utf-8")):
        if k in seen:
            continue
        if not IDENT_RE.match(k):
            raise SystemExit(f"resx key is not a C# identifier: {k!r}")
        seen.add(k)
        ordered.append(k)
    ordered.sort()

    header = [
        "// <auto-generated> by scripts/gen-strings-accessor.py — do NOT edit by hand.",
        "// Public strongly-typed accessor over Strings.resx. VS's PublicResXFileCodeGenerator",
        "// is VS-only (never runs under `dotnet build`/CI), so we own this file; the generator",
        "// keeps it in lockstep with Strings.resx and ResxAccessorParityFenceTests proves it.",
        "// Re-run: python scripts/gen-strings-accessor.py",
        "",
        "using System.Globalization;",
        "using System.Resources;",
        "",
        "namespace ROROROblox.App.Properties;",
        "",
        "/// <summary>",
        "/// UI string catalog. XAML references these via x:Static loc:Strings.Key; the",
        "/// ResourceManager resolves the running thread's CurrentUICulture to a satellite",
        "/// assembly (Strings.&lt;culture&gt;.resources), falling back to the neutral catalog.",
        "/// </summary>",
        "public static class Strings",
        "{",
        '    private static readonly ResourceManager Rm =',
        '        new("ROROROblox.App.Properties.Strings", typeof(Strings).Assembly);',
        "",
        "    /// <summary>Resolve a key for the current UI culture (neutral fallback). Public so a",
        "    /// runtime code path can read the same catalog the XAML does.</summary>",
        "    public static string Get(string key) =>",
        "        Rm.GetString(key, CultureInfo.CurrentUICulture) ?? key;",
        "",
        f"    // === {len(ordered)} generated properties — do not edit by hand ===",
    ]
    props = [f'    public static string {k} => Get("{k}");' for k in ordered]
    OUT.write_text("\n".join(header + props) + "\n}\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} — {len(ordered)} keys")


if __name__ == "__main__":
    main()
