#!/usr/bin/env python3
"""Generate About/Marks/Marks.xaml from the extracted mark geometry (v1.33 item 10).

Generated rather than hand-edited because the two marks are ~65 KB of path data between them, which
no one should be diffing or re-indenting by hand. Re-run after changing either source.

    python scripts/gen-about-marks-xaml.py

FillRule is Nonzero, explicitly. WPF's PathGeometry defaults to EvenOdd while SVG defaults to
Nonzero, and these paths came out of an SVG pen — leaving the default would silently fill the
counters of letters like o, e and a on any contour that overlaps.
"""
from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MARKS = ROOT / "src" / "ROROROblox.App" / "About" / "Marks"

HEADER = '''<!-- GENERATED by scripts/gen-about-marks-xaml.py — do not hand-edit.

     The two drawn marks on the About page (v1.33 item 10), as geometry rather than images.

     WHY GEOMETRY AND NOT A PNG: the avatar pattern this item cited commits a rendered PNG, which
     suits a 256px circle-cropped character. These are wordmarks with a 40px floor that must stay
     crisp on any DPI, and WPF draws a Path natively — so a raster step would only lose fidelity.
     It also means no rasteriser in the toolchain, which this box does not have.

     WHY NEITHER NEEDS EsteFont Pro IN THE BINARY: both are outlines. The 626Labs wordmark comes
     from the design skill's already-outlined official SVG (the brand rule is "use the files, do not
     retype it"); "Koii 4 eva" was converted from EsteFont Pro Bold to paths once, by
     scripts/make-koii-mark.py. The licensed brand face ships nowhere.

     FillRule="Nonzero" is deliberate — see the generator's note.
-->
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

'''

ENTRIES = [
    (
        "Mark626LabsWordmark",
        "626labs-wordmark.path.txt",
        '''    <!-- "626Labs" in Este's hand plus "LLC" in Space Grotesk 600, the lockup the brand reserves
         for where the legal entity is meant. Lifted from assets/Logos/626labs-wordmark-dark.svg;
         the two figures are the hand and the LLC, composed into one geometry so the lockup cannot
         drift apart. Filled from the theme's own text brush rather than the asset's baked #ffffff,
         so it follows all four built-in themes (every one of them a dark ground, which is the ink
         the Logos README assigns -dark to) and stays legible on a user-authored light theme too. -->''',
    ),
    (
        "MarkKoii4Eva",
        "koii-4-eva.path.txt",
        '''    <!-- The easter egg's reveal, in Este's hand. This is the page's one duo moment: the brand
         reserves the cyan-to-magenta gradient for "dark marquee moments only, one per page", so the
         gradient lives here and the 626Labs wordmark above stays single-ink. -->''',
    ),
]


def main() -> None:
    parts = [HEADER]
    for key, filename, comment in ENTRIES:
        src = MARKS / filename
        if not src.is_file():
            raise SystemExit(f"missing {src.relative_to(ROOT)} — run the extractor/generator first")
        figures = " ".join(line.strip() for line in src.read_text(encoding="utf-8").splitlines() if line.strip())
        if not figures:
            raise SystemExit(f"{filename} is empty")
        parts.append(comment + "\n")
        parts.append(f'    <PathGeometry x:Key="{key}" FillRule="Nonzero" Figures="{figures}" />\n\n')
    parts.append("</ResourceDictionary>\n")

    out = MARKS / "Marks.xaml"
    out.write_text("".join(parts), encoding="utf-8")
    kb = out.stat().st_size / 1024
    print(f"wrote {out.relative_to(ROOT)} — {len(ENTRIES)} geometries, {kb:.1f} KB")


if __name__ == "__main__":
    sys.exit(main())
